# Generated by Django 4.0 on 2023-03-29 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismingiz')),
                ('email', models.EmailField(max_length=100, verbose_name='Email manzil')),
                ('text', models.TextField(verbose_name='Xabar matni')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
