# Generated by Django 4.0 on 2023-04-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contact_alter_news_published_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time']},
        ),
    ]
