# Generated by Django 4.0 on 2023-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Foydalanuvchi tugilgan sana'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImages/'),
        ),
    ]
